# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'fileutils'

def local_cache(basebox_name)
  cache_dir = Vagrant::Environment.new.home_path.join('cache', 'apt', basebox_name)
  partial_dir = cache_dir.join('partial')
  FileUtils.mkdir_p(partial_dir) unless partial_dir.exist?
  cache_dir
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 5000, host: 5000 # sief-Back
  config.vm.network "forwarded_port", guest: 8983, host: 9983 # Solr
  config.vm.network "forwarded_port", guest: 15672, host: 15672 # WebView RabbitMQ


  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../", "/vagrant/sief-back"

  cache_dir = local_cache(config.vm.box)
  config.vm.synced_folder cache_dir, "/var/cache/apt/archives/"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    cd /vagrant/sief-back
    bash env_setup/provision.sh
  SHELL
end
